### ISSUE TITLE
Browser Extension Chrome Link is dead

### ISSUE THREAD

**Issue by rishaanp** [Darkle/MarkSearch-Chrome-Extension#1]
The Browser Extension Link is dead now. (https://chrome.google.com/webstore/detail/marksearch-browser-extens/apfcialnncnhpohmofpigaclihopfeng). I tried loading the package from source but ran into some trouble with the options page. Do you have the .crx?

**Comment by Darkle** [comment]
Yeah sorry, it got taken down cause I hadn't added a privacy policy (i just hadn't gotten around to it). I've added it and emailed them so hopefully it will be back up in a few days.

https://github.com/Darkle/MarkSearch#privacy-policy

**Comment by Darkle** [comment]
It's back up.
